import type { System } from "./types";

export const experienceSystem: System = {
  id: "experience",
  index: 1,
  title: "Experience",
  subtitle: "5 roles · 2 incoming",
  accent: "violet",
  accentHex: "#c4b5fd",
  planets: [
    {
      id: "candlefish",
      kind: "experience",
      label: "Candlefish",
      orbit: "inner",
      role: "Software Engineer (Applied ML)",
      company: "Candlefish — Machine Learning @UVA",
      dateRange: "Nov 2025 — May 2026",
      status: "active",
      bullets: [
        "Designed a data synthesis engine that auto-generated 10K architectural blueprints with labeled structural elements, eliminating a 200+ hour manual labeling bottleneck.",
        "Built a PyTorch U-Net segmentation model achieving 0.89 mean IoU across 6 blueprint classes with 18ms inference time.",
      ],
    },
    {
      id: "mantech",
      kind: "experience",
      label: "ManTech",
      orbit: "mid",
      role: "Software Development Intern",
      company: "ManTech",
      dateRange: "May 2025 — April 2026",
      status: "past",
      bullets: [
        "Built 4 Django microservices deployed on Google Kubernetes Engine, serving 1,000+ DoD users across 100+ worldwide locations with resilient, monitored services.",
        "Built an AI query system using LangGraph and Gemini Flash that translates natural language into complex database searches, reducing query time from 90 seconds to 20 seconds.",
        "Created an AI pipeline using OCR and Gemini to process 200+ vehicle label images per batch, cutting data-entry time from 2+ hours to 10 minutes.",
        "Developed 5 React interfaces that streamlined workflows from 8 steps to 4, improving data-entry efficiency by 50%.",
      ],
    },
    {
      id: "myedmaster",
      kind: "experience",
      label: "MyEdMaster",
      orbit: "outer",
      role: "Software Development Intern",
      company: "MyEdMaster",
      dateRange: "May 2024 — Aug 2024",
      status: "past",
      bullets: [
        "Built a personalized AI tutoring system using LangChain, GPT-4, and ChromaDB that adapts to individual student learning styles for AP Calculus and algebra.",
        "Created an automated pipeline using Selenium and BeautifulSoup to extract and structure educational content from web sources for AI-powered tutoring.",
      ],
    },
    {
      id: "fanniemae",
      kind: "experience",
      label: "Fannie Mae",
      sublabel: "☄ Incoming · Jun 2026",
      orbit: "comet",
      accent: "#a5f3fc",
      role: "Software Engineering Intern",
      company: "Fannie Mae",
      dateRange: "Jun 2026 — Aug 2026",
      status: "incoming",
      bullets: ["Incoming June 2026 · Reston, VA"],
    },
    {
      id: "ibm",
      kind: "experience",
      label: "IBM",
      sublabel: "☄ Incoming · Aug 2026",
      orbit: "comet",
      accent: "#fef08a",
      role: "Software Development Intern",
      company: "IBM",
      dateRange: "Aug 2026 — Dec 2026",
      status: "incoming",
      bullets: ["Incoming August 2026 · Austin, TX"],
    },
  ],
};
