import type { System } from "./types";

export const experienceSystem: System = {
  id: "experience",
  index: 1,
  title: "Experience",
  subtitle: "4 roles · 2 active",
  accent: "violet",
  accentHex: "#c4b5fd",
  planets: [
    {
      id: "mantech",
      kind: "experience",
      label: "ManTech",
      orbit: "inner",
      role: "Software Development Intern",
      company: "ManTech",
      dateRange: "2024 — Present",
      status: "active",
      bullets: [
        "Migrating a legacy DoD system used at 100+ locations worldwide to a modern microservices architecture using Django, React, GCP, PostgreSQL, and AI.",
        "Built an AI query system using LangGraph and Gemini Flash that translates natural language into complex database searches, reducing query time from 3 minutes to 20 seconds.",
        "Built 4 Django microservices with GraphQL and PostgreSQL with resilient, monitored services.",
        "Created an AI pipeline using OCR and Gemini to process vehicle label images, cutting data entry time from 2+ hours to 10 minutes per batch.",
        "Developed React interfaces that streamlined workflows from 8 steps to 4, improving data-entry efficiency by 50%.",
      ],
    },
    {
      id: "candlefish",
      kind: "experience",
      label: "Candlefish",
      orbit: "inner",
      role: "Software Engineer (Applied ML)",
      company: "Candlefish",
      dateRange: "Nov 2025 — Present",
      status: "active",
      bullets: [
        "Designed a data synthesis engine that auto-generated 10K architectural blueprints with labeled structural elements, eliminating a 200+ hour manual labeling bottleneck.",
        "Built a PyTorch U-Net segmentation model achieving 0.89 mean IoU across 6 blueprint classes with 18ms inference time.",
      ],
    },
    {
      id: "myedmaster",
      kind: "experience",
      label: "MyEdMaster",
      orbit: "mid",
      role: "Software Development Intern",
      company: "MyEdMaster",
      dateRange: "May 2024 — Aug 2024",
      status: "past",
      bullets: [
        "Built a personalized AI tutoring system using LangChain, GPT-4, and ChromaDB that adapts to individual student learning styles for AP Calculus and algebra.",
        "Created an automated pipeline using Selenium and BeautifulSoup to extract and structure educational content from web sources for AI-powered tutoring.",
      ],
    },
    {
      id: "ibm",
      kind: "experience",
      label: "IBM",
      sublabel: "☄ Incoming · Aug 2026",
      orbit: "comet",
      accent: "#fef08a",
      role: "Software Development Intern",
      company: "IBM",
      dateRange: "Incoming Aug 2026",
      status: "incoming",
      bullets: ["Incoming August 2026"],
    },
  ],
};
