import type { System } from "./types";

export const projectsSystem: System = {
  id: "projects",
  index: 2,
  title: "Projects",
  subtitle: "3 systems · built from scratch",
  accent: "amber",
  accentHex: "#fbbf24",
  planets: [
    {
      id: "argus",
      kind: "project",
      label: "Argus",
      orbit: "inner",
      name: "Argus",
      description: "A tool that catches silent LLM behavior shifts — model updates that break apps without triggering a single error — by detecting drift and alerting teams via Slack and a live dashboard.",
      tags: ["Python", "Go", "Next.js", "FastAPI", "PostgreSQL", "AWS", "Terraform"],
      howItWorks: "Published argus-sdk on PyPI: wraps any Anthropic/OpenAI client in one line to automatically detect when an LLM silently changes behavior, alerting teams via Slack and a live Next.js dashboard with zero added latency. Detects drift via Mann-Whitney U tests, achieving 88% accuracy at a 20% output shift with hysteresis filtering.",
      design: "Deployed on AWS via Terraform using ECS Fargate, RDS, ALB, CloudFront/S3, and GitHub Actions for CI/CD. The SDK, evaluator, and analytics service are independently deployable.",
      challenges: "Choosing Mann-Whitney U (non-parametric) was critical — LLM score distributions are rarely normal, so t-tests produce false positives. Hysteresis filtering was needed to prevent alert storms on noisy models.",
    },
    {
      id: "gitguard",
      kind: "project",
      label: "GitGuard",
      orbit: "mid",
      name: "GitGuard",
      description: "A multi-agent system that autonomously reviews GitHub repositories for security issues, performance problems, and documentation gaps — cutting manual review time by ~30 minutes per repo.",
      tags: ["LangGraph", "Claude Sonnet", "FastAPI", "PostgreSQL", "Docker", "AWS"],
      howItWorks: "A 3-agent LangGraph system (security scanning, performance optimization, documentation generation) analyzes repositories in parallel. Agent context retrieval accuracy was improved by ~40% across 5K+ line codebases by replacing naive chunking with a dependency-aware code graph via AST parsing.",
      design: "Deployed on AWS EC2, handling 3-5 concurrent analysis requests with <8s median response time per agent. FastAPI serves the orchestration layer with PostgreSQL for persisting analysis results.",
      challenges: "Naive chunking caused agents to miss cross-file dependencies in large codebases. Building a dependency-aware code graph via AST parsing was the key insight that improved retrieval accuracy by ~40%.",
    },
    {
      id: "featherdb",
      kind: "project",
      label: "FeatherDB",
      orbit: "outer",
      name: "FeatherDB",
      description: "A lightweight, file-based relational database engine built from the ground up in Java, with a custom SQL-like query language, recursive descent parser, and B-tree-indexed storage.",
      tags: ["Java", "Gradle", "JUnit"],
      github: "https://github.com/whozpj/featherdb",
      howItWorks: "A recursive descent parser converts SQL-like input into an abstract syntax tree, which a polymorphic command dispatcher routes across 8 operations (SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, and more). Data is persisted in a custom file format and indexed with B-trees for O(log n) lookups.",
      design: "Layered architecture: Parser → Command Dispatcher (polymorphic per operation) → Execution Engine → Storage Layer. Each table lives in its own file; B-tree indices are memory-resident and periodically flushed. 104 JUnit tests exercise the engine across 1K–100K-row datasets to validate correctness and performance.",
      challenges: "Implementing a recursive descent parser that handled precedence, nesting, and error recovery cleanly was the hardest piece. Maintaining O(log n) guarantees under inserts and deletes required careful B-tree rebalancing. Writing 104 tests forced meticulous boundary-condition reasoning across dataset sizes.",
    },
  ],
};
