import type { System } from "./types";

export const projectsSystem: System = {
  id: "projects",
  index: 2,
  title: "Projects",
  subtitle: "4 systems · built from scratch",
  accent: "amber",
  accentHex: "#fbbf24",
  planets: [
    {
      id: "featherdb",
      kind: "project",
      label: "FeatherDB",
      orbit: "inner",
      name: "FeatherDB",
      description: "A lightweight, file-based relational database engine built from the ground up in Java. FeatherDB implements a custom SQL-like query language with a complete parser, query optimizer, and execution engine, using the file system for persistent data storage.",
      tags: ["Java", "Maven", "JUnit"],
      github: "https://github.com/whozpj/featherdb",
      howItWorks: "FeatherDB is built with a custom SQL parser that processes queries into an abstract syntax tree. The query optimizer analyzes the execution plan and selects the most efficient path. Data is stored in a custom file format with B-tree indexing for fast lookups. The execution engine processes SELECT, INSERT, UPDATE, and DELETE operations with transaction support.",
      design: "The architecture follows a layered design pattern: Parser Layer → Optimizer → Execution Engine → Storage Layer. Each layer is modular and testable. The file system acts as the persistent storage, with each table stored as a separate file. Indexes are maintained in memory and periodically flushed to disk.",
      challenges: "Implementing a robust query parser that handles complex SQL syntax was challenging. Ensuring data consistency during concurrent operations required careful transaction management. Optimizing query performance without a traditional database cache required innovative indexing strategies.",
    },
    {
      id: "gitguard",
      kind: "project",
      label: "GitGuard",
      orbit: "mid",
      name: "GitGuard",
      description: "Multi-agent AI-powered code analysis platform that automatically reviews GitHub repositories to identify security vulnerabilities, optimize performance, and generate documentation using LLMs.",
      tags: ["LangChain", "Llama 3.1", "FastAPI", "Python", "PostgreSQL", "Pinecone", "Docker", "Heroku"],
      howItWorks: "GitGuard uses LangChain to orchestrate three specialized agents—security scanning, performance optimization, and documentation generation—powered by Llama 3.1 via the Groq API. A RAG pipeline with Pinecone vector embeddings provides context-aware suggestions by retrieving relevant code snippets. GitHub webhooks trigger analysis on pull requests, and results are stored in PostgreSQL.",
      design: "The system follows a microservices-style architecture with FastAPI as the backend, PostgreSQL for persistent storage, and Pinecone for semantic search. GitHub API integrations handle repository access and webhook events. The application is containerized with Docker and deployed on Heroku for scalability and reliability.",
      challenges: "Designing effective agent specialization required careful prompt engineering. Achieving high accuracy in detecting SQL injection vulnerabilities involved tuning retrieval and evaluation logic. Managing webhook concurrency and ensuring low-latency responses under load were key deployment challenges.",
    },
    {
      id: "mlb",
      kind: "project",
      label: "MLB Pitcher Injury Predictor",
      orbit: "mid",
      name: "MLB Pitcher Injury Predictor",
      description: "A real-time injury monitoring system for MLB pitchers that analyzes pitch sequences to predict potential injuries before they occur.",
      tags: ["Python", "PyTorch", "FastAPI", "React", "PostgreSQL", "MLB Statcast", "AWS"],
      howItWorks: "Continuously monitors MLB pitchers by analyzing their pitch velocity, spin rate, and release mechanics from every game. The system detects subtle biomechanical changes that often precede injuries, providing early warnings 2-3 starts before problems occur.",
      design: "An ETL pipeline ingests real-time pitch data from MLB Statcast API, preprocessing 200K+ sequences into time-series features. An LSTM autoencoder learns normal pitching patterns and flags anomalies indicating injury risk. The FastAPI backend serves predictions stored in PostgreSQL (RDS), with model artifacts on S3 and the React dashboard deployed on AWS EC2.",
    },
    {
      id: "animal",
      kind: "project",
      label: "Animal Behavior Recognition",
      orbit: "outer",
      name: "Animal Behavior Recognition System",
      description: "A computer vision system that detects, counts, and tracks animals in images and videos while classifying their poses to identify and monitor behaviors over time.",
      tags: ["Python", "OpenCV", "PyTorch"],
      howItWorks: "Detects animals per-frame with a trained object-detection head, then tracks instances across frames. A pose classifier labels body configuration at each detection to infer behavior categories.",
      design: "Python + OpenCV pipeline feeds PyTorch models. Tracking assigns stable IDs across frames; pose classification emits behavior labels per track; aggregated over time for monitoring.",
    },
  ],
};
